use next.js's official example

diff --git a/frontend/Dockerfile b/frontend/Dockerfile
--- a/frontend/Dockerfile
+++ b/frontend/Dockerfile
@@ -1,35 +1,69 @@
-# Stage 1: Building the code
-FROM node:18-alpine AS builder
+# Reference: https://github.com/vercel/next.js/tree/canary/examples/with-docker
 
+FROM node:18-alpine AS base
+
+# Install dependencies only when needed
+FROM base AS deps
+# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
+RUN apk add --no-cache libc6-compat
 WORKDIR /app
 
-# Copy the package.json and package-lock.json
-COPY package*.json ./
+# Install dependencies based on the preferred package manager
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+RUN \
+   if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+   elif [ -f package-lock.json ]; then npm ci; \
+   elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
+   else echo "Lockfile not found." && exit 1; \
+   fi
 
-# Install dependencies
-RUN npm install --legacy-peer-deps
 
-# Copy the app source code
+# Rebuild the source code only when needed
+FROM base AS builder
+WORKDIR /app
+COPY --from=deps /app/node_modules ./node_modules
 COPY . .
 
-# Build the app
-RUN npm run build
+# Next.js collects completely anonymous telemetry data about general usage.
+# Learn more here: https://nextjs.org/telemetry
+# Uncomment the following line in case you want to disable telemetry during the build.
+# ENV NEXT_TELEMETRY_DISABLED 1
 
-# Stage 2: Run the app
-FROM node:18-alpine AS runner
+RUN \
+   if [ -f yarn.lock ]; then yarn run build; \
+   elif [ -f package-lock.json ]; then npm run build; \
+   elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
+   else echo "Lockfile not found." && exit 1; \
+   fi
+
+# Production image, copy all the files and run next
+FROM base AS runner
 WORKDIR /app
 
-# Copy built assets from the builder stage
-COPY --from=builder /app/.next/ .next/
-COPY --from=builder /app/node_modules/ node_modules/
-COPY --from=builder /app/public/ public/
-COPY --from=builder /app/package.json package.json
+ENV NODE_ENV production
+# Uncomment the following line in case you want to disable telemetry during runtime.
+# ENV NEXT_TELEMETRY_DISABLED 1
 
-# Expose the port Next.js runs on
+RUN addgroup --system --gid 1001 nodejs
+RUN adduser --system --uid 1001 nextjs
+
+COPY --from=builder /app/public ./public
+
+# Set the correct permission for prerender cache
+RUN mkdir .next
+RUN chown nextjs:nodejs .next
+
+# Automatically leverage output traces to reduce image size
+# https://nextjs.org/docs/advanced-features/output-file-tracing
+COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
+COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
+
+USER nextjs
+
 EXPOSE 3000
 
-# Set environment to production to avoid including unnecessary files
-# ENV NODE_ENV development
+ENV PORT 3000
 
-# Start the app
-CMD ["npm", "start"]
+# server.js is created by next build from the standalone output
+# https://nextjs.org/docs/pages/api-reference/next-config-js/output
+CMD HOSTNAME="0.0.0.0" node server.js
